# Copyright 2019 Observational Health Data Sciences and Informatics
#
# This file is part of Argos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Calculate Years of Life Lost (YLL), Years Lost due to Disability (YDD), and Disability-Adjusted Life Year (DALY)
#' @param outcomeData                  outcomeData generated by Argos package.
#' @param refLifeExpectancy        reference  life expectancy data to calculate YDD. The default life expectancy table is provided and can be loaded via loadLifeExpectancy function
#' @param disabilityWeight         disability weight for the certain condition of plpData to calculate YLD. if this is 0, YLD is 0. It should be float value (0~1).
#' @param outcomeDisabilityWeight   Disability weight for outcome.  If the outcome is death, then disability weight should be 1. It should be float value (0~1).
#' @param minTimeAtRisk            time at risk (days). usually it should be identical to the minTAR of plpData
#' @param discount                 discount value, float(0~1). default value is 0.3.
#' @param ageWeghting               logical value (TRUE or FALSE). 
#' @param outputFolder             outputFolder
#' 
#' @export
calculateDALY <- function (outcomeData,
                           refLifeExpectancy,
                           disabilityWeight=0,
                           outcomeDisabilityWeight = 1,
                           minTimeAtRisk,
                           discount = 0.3,
                           ageWeghting =TRUE,
                           outputFolder){
    
    #load covariates
    #limit covariates of plpData to the population
    covariates<-ff::as.ram(limitCovariatesToPopulation(covariates = outcomeData$plpData$covariates,rowIds = ff::as.ff(outcomeData$population$rowId)))
    #load covariate reference
    covRef<-ff::as.ram(outcomeData$plpData$covariateRef)
    #limit covarite Ref to the existing covarites in the population
    covRef <- covRef [covRef$covariateId %in% unique(covariates$covariateId), ]
    cohort<-outcomeData$population
    
    #make a age, age at outcome, and then life expectancy at the age of outcome
    
    cohort %>% 
        mutate(startYear = lubridate::year(cohortStartDate)) %>%
        mutate(ageAtOutcome) = age + round(daysToEvent/365,0)
    
    refLifeExpectancy= loadLifeExpectancy('KOR')
    
    #calculate YLL (Years of Life Lost)
    ydd = burden(disabilityWeight= 1.00, 
                 disabilityStartAge=ageAtOutcome, 
                 duration= chort$lifeExpAtOutcome, 
                 ageWeighting=ageWeighting, 
                 discount=discount, 
                 age=cohort$age)
    
    yld = burden(disabilityWeight= disabilityWeight, 
                 disabilityStartAge = cohort$startYear, 
                 duration=cohort$survivalTime/365, 
                 ageWeighting=ageWeighting, 
                 discount=discount, 
                 age=cohort$age)
    
    #age at onset
    #duration of disease
    
    #Age 
    #Age at death
    #
    
    #life Expectancy at the age of the death
    #age at death

    result = data.frame(yllSum = sum(yll,na.rm =TRUE),
                        yldSum = sum(yld,na.rm =TRUE),
                        dalySum = sum(yll,na.rm =TRUE) + sum(yld,na.rm =TRUE),
                        yllPerEvent = mean(yll, na.rm = TRUE),
                        yldPerEvent = mean(yld, na.rm = TRUE),
                        dalyPerEvent = mean(yll,na.rm =TRUE) + mean(yld,na.rm =TRUE))
    
    return (result)
}

##Helper function for calculating integral in DALY function
f<-function(x,ageWeighting,C = 0.1658, beta = 0.04, discount, age){
    ageWeighting * C *x *exp(-beta*x)*exp(-discount*(x-age))+ (1-ageWeighting)*exp(-discount*(x-age))
}

#'Burden calculation function
#'@param disabilityWeight
#'@param disabilityStartAge
#'@param duration
#'@param ageWeighting
#'@param discount
#'@param age
#'@export
burden <- function(disabilityWeight,
                   disabilityStartAge,
                   duration,
                   ageWeighting,
                   discount,
                   age){
    burdenValue=disabilityWeight * integrate(f, lower = disabilityStartAge, upper = disabilityStartAge+duration, ageWeighting=ageWeighting, discount=discount, age=age )$value
    return(burdenValue)
}

