# Copyright 2019 Observational Health Data Sciences and Informatics
#
# This file is part of Argos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Calculate Years of Life Lost (YLL), Years Lost due to Disability (YDD), and Disability-Adjusted Life Year (DALY)
#' @param plpData                  plpData generated by PLP package.
#' @param population               population data generated by PLP package. the outcome should be death
#' @param refLifeExpectancy        reference  life expectancy data to calculate YDD
#' @param disabilityWeight         disability weight for the certain condition of plpData to calculate YLD. if this is 0, YLD is 0
#' @param minTimeAtRisk            time at risk (days). usually it should be identical to the minTAR of plpData
#' @param discount                 discount count, float(0~1). default value is 0.3
#' @param outputFolder             outputFolder
#' 
#' @export
calculateDALY <- function (plpData,
                           population,
                           refLifeExpectancy,
                           disabilityWeight=0,
                           minTimeAtRisk,
                           discount,
                           outputFolder){
    #calculate YLL (Years of Life Lost)
    
    
    #calculate YLD (Years Lost due to Disability)
    if (disabilityWeight ==0) {
        yld <-0
        } else {
    }
    
    daly = yll+yld
    
    return (list(daly=daly,
                 yll=yll,
                 yld=yld))
}
